.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/msg/gcms/ui/component/intro/IntroActivity.kt
app/src/main/java/com/msg/gcms/ui/component/login/LoginFragment.kt
app/src/main/java/com/msg/gcms/ui/component/registration/RegistrationFragment.kt
app/src/main/res/layout/activity_intro.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_profile.xml
app/src/main/res/layout/fragment_add_member.xml
app/src/main/res/layout/fragment_club_detail.xml
app/src/main/res/layout/fragment_club_home.xml
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_make_club.xml
app/src/main/res/layout/fragment_registration.xml
app/src/main/res/layout/item_my_club.xml
app/src/main/res/layout/list_club_member.xml
app/src/main/res/layout/list_search_member.xml

⚙ :: 코드 정리 및 로그인, 회원가입

---

app/src/main/java/com/msg/gcms/ui/component/club/home/HomeFragment.kt
app/src/main/res/layout/fragment_club_home.xml

🔀 :: Data Binding 오류 해결

---

app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Login.kt
app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Logout.kt
app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Refresh.kt
app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Register.kt
app/src/main/java/com/msg/gcms/data/remote/dto/datasource/auth/Verify.kt

(#46)🔀 :: auth dataclass 생성

---

app/build.gradle.kts
app/src/main/res/values/strings.xml
build.gradle.kts

🔀 :: string, gradle 파일 수정

---

app/src/main/java/com/msg/gcms/data/remote/dto/datasource/base/BaseRequest.kt
app/src/main/java/com/msg/gcms/ui/component/emailcheck/EmailCheckFragment.kt

🔀 :: BaseRequest 파일 생성

---

app/src/main/java/com/msg/gcms/ui/component/intro/IntroActivity.kt
app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
app/src/main/res/layout/fragment_make_club_detail.xml

🔀 (78) :: 뒤로 가기 페이지 설정

---

app/src/main/java/com/msg/gcms/data/remote/datasource/CommonDataSource.kt
app/src/main/java/com/msg/gcms/data/remote/datasource/CommonDataSourceImpl.kt
app/src/main/java/com/msg/gcms/data/remote/network/CommonAPI.kt
app/src/main/java/com/msg/gcms/data/remote/network/loginInterceptor.kt
app/src/main/java/com/msg/gcms/data/repository/CommonRepositoryImpl.kt
app/src/main/java/com/msg/gcms/domain/repository/CommonRepository.kt
app/src/main/java/com/msg/gcms/domain/usecase/common/RegistrationUseCase.kt
app/src/main/java/com/msg/gcms/ui/component/emailcheck/EmailCheckFragment.kt
app/src/main/java/com/msg/gcms/ui/component/postemail/PostEmailFragment.kt
app/src/main/java/com/msg/gcms/ui/component/signUp/SignUpFragment.kt
app/src/main/java/com/msg/viewmodel/RegistrationViewModel.kt

 🔀 (#89) :: 회원가입

---

.idea/misc.xml
app/src/main/java/com/msg/gcms/data/remote/datasource/CommonDataSourceImpl.kt
app/src/main/java/com/msg/gcms/data/remote/network/CommonAPI.kt
app/src/main/java/com/msg/gcms/data/repository/CommonRepositoryImpl.kt
app/src/main/java/com/msg/gcms/domain/repository/CommonRepository.kt
app/src/main/java/com/msg/gcms/domain/usecase/common/RegistrationUseCase.kt
app/src/main/java/com/msg/gcms/ui/component/signUp/SignUpFragment.kt
app/src/main/java/com/msg/viewmodel/RegistrationViewModel.kt
app/src/main/res/layout/activity_intro.xml
app/src/main/res/layout/fragment_sign_up.xml
app/src/main/res/values/strings.xml

🔀 (#91) :: 회원가입 잘못된 값 보내던 오류 수정

---

.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubIntroduce/ClubIntroduceFragment.kt
app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubType/ClubTypeFragment.kt
app/src/main/java/com/msg/gcms/ui/component/emailcheck/EmailCheckFragment.kt
app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
app/src/main/java/com/msg/gcms/ui/component/signUp/SignUpFragment.kt
app/src/main/java/com/msg/viewmodel/RegistrationViewModel.kt
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/fragment_application.xml
app/src/main/res/layout/fragment_club_introduce.xml
app/src/main/res/layout/fragment_club_type.xml
app/src/main/res/layout/fragment_make_club_detail.xml
app/src/main/res/layout/fragment_sign_up.xml
app/src/main/res/navigation/registration_graph.xml

🐛 (#93) :: smail error complite

---

.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/inspectionProfiles/ktlint.xml
.idea/inspectionProfiles/profiles_settings.xml
.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/msg/gcms/base/di/GCMSApplication.kt
app/src/main/java/com/msg/gcms/base/di/module/DataSourceModule.kt
app/src/main/java/com/msg/gcms/base/di/module/NetworkModule.kt
app/src/main/java/com/msg/gcms/base/di/module/RepositoryModule.kt
app/src/main/java/com/msg/gcms/base/di/module/UserCaseModule.kt
app/src/main/java/com/msg/gcms/base/utils/Event.kt
app/src/main/java/com/msg/gcms/data/remote/network/CommonAPI.kt
app/src/main/java/com/msg/gcms/data/remote/network/loginInterceptor.kt
app/src/main/java/com/msg/gcms/domain/usecase/common/RegistrationUseCase.kt
app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
app/src/main/java/com/msg/gcms/ui/component/emailcheck/EmailCheckFragment.kt
app/src/main/java/com/msg/gcms/ui/component/main/MainActivity.kt
app/src/main/java/com/msg/gcms/ui/component/postemail/PostEmailFragment.kt
app/src/main/java/com/msg/gcms/ui/component/signUp/SignUpFragment.kt
app/src/main/java/com/msg/gcms/ui/dialog/EmailFailureDialogFragment.kt
app/src/main/java/com/msg/viewmodel/MainViewModel.kt
app/src/main/java/com/msg/viewmodel/MakeClubViewModel.kt
app/src/main/java/com/msg/viewmodel/RegistrationViewModel.kt

이벤트 Wrapper를 사용하여, LiveData 의 VIewModel 에 맞춘 LIfecycle에 의해 나타나는 오류를 변경하였습니다.

🔀 (#98) :: EventWrapper 사용

---

.idea/misc.xml
app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/MemberInfo.kt
app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/response/MemberSummaryResponse.kt
app/src/main/java/com/msg/gcms/ui/adapter/ActivityPhotosAdapter.kt
app/src/main/java/com/msg/gcms/ui/adapter/ClubMemberAdapter.kt
app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
app/src/main/res/layout/fragment_make_club_detail.xml
app/src/main/res/layout/list_club_member.xml

* RecyclerView를 사용하기 위한 Adapter 를 구현합니다.
https://github.com/GSM-MSG/GCMS-Android/blob/9d06df8041e02f105e1f097d9c4024afd8ba3f89/app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt#L81-L96
* RecyclerView 아이템을 클릭하였을 시에 나오는 이벤트를 생성합니다.
https://github.com/GSM-MSG/GCMS-Android/blob/9d06df8041e02f105e1f097d9c4024afd8ba3f89/app/src/main/java/com/msg/gcms/ui/adapter/ClubMemberAdapter.kt#L22-L57

🔀  :: (#142)Club Member RecyclerView 구현

---

.idea/deploymentTargetDropDown.xml
app/src/main/java/com/msg/gcms/data/remote/datasource/ImageDataSource.kt
app/src/main/java/com/msg/gcms/data/remote/datasource/ImageDataSourceImpl.kt
app/src/main/java/com/msg/gcms/data/remote/dto/datasource/Image/ImageResponse.kt
app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/request/CreateClubRequest.kt
app/src/main/java/com/msg/gcms/data/remote/dto/datasource/club/request/EmailType.kt
app/src/main/java/com/msg/gcms/data/remote/network/ImageAPI.kt
app/src/main/java/com/msg/gcms/data/repository/ImageRepositoryImpl.kt
app/src/main/java/com/msg/gcms/domain/repository/ImageRepository.kt
app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt
app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubIntroduce/ClubIntroduceFragment.kt
app/src/main/java/com/msg/gcms/ui/component/clubmaker/searchstudent/StudentSearchFragment.kt
app/src/main/java/com/msg/viewmodel/MainViewModel.kt
app/src/main/java/com/msg/viewmodel/MakeClubViewModel.kt
app/src/main/res/layout/fragment_make_club_detail.xml

* 동아리 생성 기능을 구현합니다.
https://github.com/GSM-MSG/GCMS-Android/blob/4521446e585c188eb4ee7c7dd5f36bd044225d0d/app/src/main/java/com/msg/gcms/ui/component/clubmaker/clubDetail/MakeClubDetailFragment.kt#L63-L84

⚡️ :: (#164) 동아리 생성 기능 구현

---

.idea/deploymentTargetDropDown.xml
app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt

🔀 :: (#194)로그 삭제

---

app/src/main/java/com/msg/gcms/data/remote/datasource/ClubDataSource.kt
app/src/main/java/com/msg/gcms/data/remote/datasource/ClubDataSourceImpl.kt
app/src/main/java/com/msg/gcms/data/remote/dto/datasource/user/request/UserDeleteRequest.kt
app/src/main/java/com/msg/gcms/data/remote/network/ClubAPI.kt
app/src/main/java/com/msg/gcms/data/remote/network/UserAPI.kt
app/src/main/java/com/msg/gcms/data/repository/ClubRepositoryImpl.kt
app/src/main/java/com/msg/gcms/domain/repository/ClubRepository.kt
app/src/main/java/com/msg/gcms/domain/usecase/club/ClubDeleteUseCase.kt
app/src/main/java/com/msg/gcms/domain/usecase/user/ExitUseCase.kt
app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt
app/src/main/java/com/msg/gcms/ui/component/profile/ProfileActivity.kt
app/src/main/java/com/msg/viewmodel/ClubViewModel.kt

- 동아리 삭제
- 동아리 탈퇴
- 동아리 삭제시
https://github.com/GSM-MSG/GCMS-Android/blob/ce303081b7d336dcb98ec89e2b91dbac9af8d63d/app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt#L229-L235
- 동아리 탈퇴시
https://github.com/GSM-MSG/GCMS-Android/blob/ce303081b7d336dcb98ec89e2b91dbac9af8d63d/app/src/main/java/com/msg/gcms/ui/component/club/detail/DetailFragment.kt#L212-L217

🔀 :: (#210) delete club

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/MakeClubViewModel.kt

🔀 :: 여러 번 요청 보내지는거 제어

---

app/src/main/java/com/msg/gcms/data/remote/datasource/AuthDataSource.kt
app/src/main/java/com/msg/gcms/data/remote/datasource/AuthDataSourceImpl.kt
app/src/main/java/com/msg/gcms/data/remote/network/AuthAPI.kt
app/src/main/java/com/msg/gcms/data/repository/AuthRepositoryImpl.kt
app/src/main/java/com/msg/gcms/di/module/UseCaseModule.kt
app/src/main/java/com/msg/gcms/domain/repository/AuthRepository.kt
app/src/main/java/com/msg/gcms/domain/usecase/auth/LogoutUseCase.kt
app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/AuthViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/ProfileViewModel.kt

- 로그아웃 로직을 작성합니다.
- AuthViewModel
https://github.com/GSM-MSG/GCMS-Android/blob/2b7d20c8ad894ff6818818b195b04dbbbb450001/app/src/main/java/com/msg/gcms/presentation/viewmodel/AuthViewModel.kt#L47-L59

🔀 :: (#247)로그아웃 로직 작성

---

app/src/main/java/com/msg/gcms/data/remote/network/api/ClubAPI.kt
app/src/main/java/com/msg/gcms/data/remote/network/api/UserAPI.kt

api 에 end point들이 잘못 설정되어있어 해당 사항들을 변경합니다.

🔀 :: endpoint 수정

---

.github/workflows/android.yml

ci에 캐시를 추가하였습니다.
https://github.com/GSM-MSG/GCMS-Android/blob/442360a0664d63d1d28ad47f3fa7b75fbdd5a53c/.github/workflows/android.yml#L29-L37

🔀  :: (#259) CI에 캐시 추가

---

app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubDetailViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/MainViewModel.kt

동아리 리스트 받아오는 로직 리스트 띄우도록 수정
* 동아리 정보를 가져왔는데 동아리가 없는 경우가 처리가 되어있지 않음

🔀 :: (#262) - modify call get club list

---

app/src/main/java/com/msg/gcms/data/remote/network/api/ClubAPI.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubDetailViewModel.kt

api 요청을 보내는 부분에서 휴먼 에러가 있었습니다. ㅎㅎ

🔀 :: (#264) - resolved club detail error

---

app/src/main/java/com/msg/gcms/data/mapper/ClubMapper.kt
app/src/main/java/com/msg/gcms/data/remote/dto/club/get_club_detail/ClubDetailResponse.kt
app/src/main/java/com/msg/gcms/data/remote/network/api/AuthAPI.kt
app/src/main/java/com/msg/gcms/data/remote/network/api/ClubAPI.kt
app/src/main/java/com/msg/gcms/data/remote/network/api/ClubMemberAPI.kt
app/src/main/java/com/msg/gcms/data/remote/network/api/UserAPI.kt

204 status를 사용하는 부분들을 임시 방편을 넣습니다.

🔀 :: (#268) - 204 status를 사용하는 부분들을 임시 방편을 넣습니다.

---

app/src/main/java/com/msg/gcms/data/mapper/ClubMapper.kt
app/src/main/java/com/msg/gcms/data/remote/dto/club/get_club_detail/ClubDetailResponse.kt
app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
app/src/main/res/layout/fragment_detail.xml

🔀 :: 디테일 페이지에서 부장 정보를 잘못불러오는 이슈 해결

---

app/src/main/res/drawable/bg_detail_club_link.xml
app/src/main/res/layout/fragment_detail.xml

🔀 :: 동아리 디테일 페이지 디자인 수정

---

app/src/main/java/com/msg/gcms/data/remote/dto/user/get_my_profile/ProfileClubResponse.kt

🔀 :: api 통신 부분 잘못 지정된 부분 변경

---

app/src/main/java/com/msg/gcms/presentation/adapter/activity_photo/ActivityPhotosAdapter.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt

동아리 생성할 때 동아리 사진이 안뜨던 이슈를 DiffUtil로 변경하고, 사이클을 수정하며 해결했습니다.

🔀 :: (#279) - modify adapter when create club

---

app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_detail.xml

- 디테일 페이지 스크롤 물결 삭제
- 디테일 페이지 하단의 빈공간 삭제

🔀 :: (#285) - 디테일 페이지 UI 수정

---

app/src/main/java/com/msg/gcms/presentation/adapter/club_member/ClubMemberAdapter.kt
app/src/main/java/com/msg/gcms/presentation/adapter/user_search/UserSearchAdapter.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubActivity.kt
app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/EditViewModel.kt

동아리를 수정할 때 동아리 정보를 받아오는 로직을 재구성합니다.

🔀 ::  Changed the API that receives club information when editing club information

---

app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/EditViewModel.kt

동아리 수정 시 동아리 멤버를 변경할 수 있도록 설정합니다.
https://user-images.githubusercontent.com/82383983/221348074-1a372968-ea39-4d8d-afa9-e771c6976cf8.mp4

🔀 :: (#290) - modify club member

---

.idea/deploymentTargetDropDown.xml
app/src/main/java/com/msg/gcms/data/remote/dto/applicant/get_applicant_list/GetApplicantListResponse.kt
app/src/main/java/com/msg/gcms/data/remote/dto/club_member/get_club_member/GetClubMemberResponse.kt
app/src/main/java/com/msg/gcms/data/remote/dto/club_member/get_club_member/MemberResponse.kt
app/src/main/java/com/msg/gcms/presentation/adapter/applicant/ApplicantAdapter.kt
app/src/main/java/com/msg/gcms/presentation/adapter/member/MemberAdapter.kt
app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt

동아리 유저 관리하기에서 유저, 신청자 리스트 받아오기

🔀:: (#300) get club member when club member manage

---

app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt

🔀 :: 코드 서순 바뀐거 수정

---

.idea/deploymentTargetDropDown.xml
app/src/main/java/com/msg/gcms/data/remote/dto/club/modify_club_info/ModifyClubInfoRequest.kt
app/src/main/java/com/msg/gcms/domain/data/club/modify_club_info/ModifyClubInfoData.kt
app/src/main/java/com/msg/gcms/presentation/utils/FileUtil.kt
app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/EditViewModel.kt

🔀 :: (#307) - bad req when create club

---

app/build.gradle.kts

️🔀 :: GCMS 2.0.0으로 업데이트

---

app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt

동아리 정보를 수정하는 로직을 작성합니다.
- 사진 변경, 정보 변경, 멤버 변경 모두 정상 작동 성공

️🔀 :: (#280) - change the logic that modify club infomation

---

app/src/main/java/com/msg/gcms/data/remote/dto/club_member/delegation_of_manager/DelegationOfManagerRequest.kt
app/src/main/java/com/msg/gcms/domain/data/club_member/delegation_of_manager/DelegationOfManagerData.kt
app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/MemberManageViewModel.kt

- 부장 위임 기능에서 성공은 뜨지만 실제 동작은 안하던 이슈 해결
- 맴버 리스트, 신청자 리스트, 위임 예외처리 이상한거 수정
- 맴버관리 다이얼로그들 실행되는 시점 수정
- 부장 위임을 위한 정보중 UUID를 email로 잘못 보내던 에러 수정
- 부장 위임 관련 DTO타입 UUID로 변경
- 부장 위임 예외처리
https://github.com/GSM-MSG/GCMS-Android/blob/19f8c09d6e578e92bdfdfab5f8ceb5e06769ee56/app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt#L218-L241

🔀 :: (#304) - 부장 위임 이슈 해결

---

app/src/main/java/com/msg/gcms/data/remote/network/api/ClubAPI.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/MakeClubViewModel.kt

- 동아리 생성시 NPE가 뜨는 문제 해결
- 이상한 예외처리 수정
- Response때문에 403을 성공으로 받는 이슈 해결
- 널 거르는 로직
https://github.com/GSM-MSG/GCMS-Android/blob/84424d490d70bbbfdaadd99132746326dc43ca0e/app/src/main/java/com/msg/gcms/presentation/viewmodel/MakeClubViewModel.kt#L165

🔀 :: (#317)동아리 생성 이슈 해결

---

app/build.gradle.kts
app/src/main/java/com/msg/gcms/presentation/view/splash/SplashActivity.kt
app/src/main/java/com/msg/gcms/util/VersionChecker.kt
buildSrc/src/main/java/Dependency.kt
buildSrc/src/main/java/Versions.kt

🔀 :: (#315) - in app update

---

app/build.gradle.kts
app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt
app/src/main/java/com/msg/gcms/presentation/view/splash/SplashActivity.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/AuthViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubDetailViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/EditViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/MainViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/MakeClubViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/MemberManageViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/ProfileViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/WithdrawalViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/util/ErrorHandling.kt
app/src/main/java/com/msg/gcms/util/VersionChecker.kt
buildSrc/src/main/java/Dependency.kt
buildSrc/src/main/java/Versions.kt

- 토큰 만료 시 로컬에 저장된 토큰을 제거 합니다.
- 에러 핸들링 하는 코드를 util로 만들어 재사용성을 높였습니다.
- 에러 핸들링 코드 util로 만들기
https://github.com/GSM-MSG/GCMS-Android/blob/7eeafae9e9874a5343d5b331f1ab54293f8889c8/app/src/main/java/com/msg/gcms/presentation/viewmodel/util/ErrorHandling.kt#L14-L71
- 에러 일때 함수를 실행 시키고 싶다면 파라미터로 넘깁니다.
https://github.com/GSM-MSG/GCMS-Android/blob/7eeafae9e9874a5343d5b331f1ab54293f8889c8/app/src/main/java/com/msg/gcms/presentation/viewmodel/AuthViewModel.kt#L35-L38

🔀 :: (#316) 토큰 만료 에러 핸들링

---

app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
app/src/main/java/com/msg/gcms/presentation/view/splash/SplashActivity.kt

- 스플래쉬에서 토큰이 변질되어있는지 검사합니다
- 모든 요청에서 401 발생시에 인트로 액티비티로 넘어가도록 처리했습니다.
- 스플래쉬에서 토큰이 변질되었는지 검사
https://github.com/GSM-MSG/GCMS-Android/blob/26f2afed6ccfc7ebbea584af5778db5d031482d9/app/src/main/java/com/msg/gcms/presentation/view/splash/SplashActivity.kt#L32-L56

🔀 :: (#321) - 토큰 변질 검사

---

app/src/main/java/com/msg/gcms/data/remote/network/api/ClubAPI.kt
app/src/main/java/com/msg/gcms/data/repository/ClubRepositoryImpl.kt
app/src/main/java/com/msg/gcms/domain/exception/HttpException.kt
app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubViewModel.kt

동아리 탈퇴 기능 구현
- 알수 없는 에러긴 한데 일단 통신은 됨

🔀 :: (#320) - the logic of exit club

---

app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt

🔀 :: (#328) - 디테일 페이지 예외처리 수정

---

app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/make_result/MakeClubResultFragment.kt
app/src/main/res/layout/fragment_make_club_result.xml

동아리 생성 시 케이스에 따른 화면 제어
이제 진짜 될껄

🔀 :: (#330) - modify create club message

---

app/build.gradle.kts

🔀 :: (#336) - 2.0.1 업데이트

---

app/build.gradle.kts
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt

🔀 ::(#339) 2.0.2 업그레이드

---

app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt

204 오류로 인해 해당 케이스에서만 204 오류 시 나머지를 다 거르지고 else를 성공케이스를 집계하도록 수정
- 내용을 적어주세요.

🔀 :: 동아리 거절 시 else case 수정

---

app/build.gradle.kts
app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt

🔀 :: (#351) 2.0.5 버전 업그레이드

---

app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt

🔀 :: (#354) 클럽 페이지 변경

---

app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_introduce/ClubIntroduceFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_type/ClubTypeFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/make_result/MakeClubResultFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/search_student/StudentSearchFragment.kt

🔀  :: (#354) 클럽 생성 페이지 변경

---

app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt

🔀 :: (#354) - edit club

---

app/build.gradle.kts
app/src/main/java/com/msg/gcms/presentation/utils/KeyboardEvent.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_detail/MakeClubDetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/club_introduce/ClubIntroduceFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/clubmaker/search_student/StudentSearchFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/editclub/EditClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/editclub/EditSearchFragment.kt
app/src/main/res/layout/fragment_club_introduce.xml
app/src/main/res/layout/fragment_edit_club.xml
app/src/main/res/layout/fragment_edit_search.xml
app/src/main/res/layout/fragment_student_search.xml

🔀 :: (#359) 키보드 포커스 조절

---

.idea/deploymentTargetDropDown.xml
app/build.gradle.kts
app/src/main/res/layout/activity_intro.xml

- GAuth버튼 찌그러짐 현상 해결 
- 변경사항에 맞게 버전업 후 aab 추출

🔀 :: (#363) - version 2.0.7 업데이트 (GAuth버튼 찌그러짐 수정)

---

app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
app/src/main/java/com/msg/gcms/presentation/view/progress/ProgressDialog.kt

가입 대기자 명단 불러오는 에러 해결
- applicantList의 visibility로 변경
https://github.com/GSM-MSG/GCMS-Android/blob/799a6547cfd8f401907aaf6094195ba08b73aa24/app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt#L142

🔀 :: (#367) 가입 대기자 명단 불러오는 에러 해결

---

app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt

🔀 :: (#368) - 다이얼로그 중복 생성 이슈 해결

---

app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt

🔀 :: (#373) - 클럽 리스트 받는 로직 이그노어 path추가

---

app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
buildSrc/src/main/java/Versions.kt

- 업데이트된 최신버전의 GAuth를 적용합니다.
- 버튼의 가로 사이즈를 수정합니다.

🔀 :: (#379) - GAuth v1.0.7 적용

---

.github/workflows/android.yml
.idea/deploymentTargetDropDown.xml
app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/msg/gcms/data/local/datasource/LocalDataSource.kt
app/src/main/java/com/msg/gcms/data/local/datasource/LocalDataSourceImpl.kt
app/src/main/java/com/msg/gcms/data/local/datastorage/AuthDataStorage.kt
app/src/main/java/com/msg/gcms/data/local/datastorage/AuthDataStorageImpl.kt
app/src/main/java/com/msg/gcms/data/remote/dto/auth/request/RefreshRequest.kt
app/src/main/java/com/msg/gcms/data/remote/dto/auth/request/SignInRequest.kt
app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt
app/src/main/java/com/msg/gcms/data/repository/AuthRepositoryImpl.kt
app/src/main/java/com/msg/gcms/domain/data/auth/SignInRequestData.kt
app/src/main/java/com/msg/gcms/domain/repository/AuthRepository.kt
app/src/main/java/com/msg/gcms/domain/usecase/auth/SaveTokenInfoUseCase.kt
app/src/main/java/com/msg/gcms/presentation/service/GCMSMessagingService.kt
app/src/main/java/com/msg/gcms/presentation/utils/ChangeScreenEvent.kt
app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
app/src/main/java/com/msg/gcms/presentation/view/member_manage/MemberManageActivity.kt
app/src/main/java/com/msg/gcms/presentation/view/splash/SplashActivity.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/AuthViewModel.kt
app/src/main/res/layout/fragment_detail.xml
build.gradle.kts
buildSrc/src/main/java/Dependency.kt
buildSrc/src/main/java/Versions.kt

- FCM 메시지 받기
- 멤버 관리 시 확장버튼을 다중 클릭 하는 오류 해결

🔀 :: (#378) FCM 세팅

---

app/src/main/java/com/msg/gcms/data/mapper/UserMapper.kt
app/src/main/java/com/msg/gcms/data/remote/datasource/user/UserDataSource.kt
app/src/main/java/com/msg/gcms/data/remote/datasource/user/UserDataSourceImpl.kt
app/src/main/java/com/msg/gcms/data/remote/dto/user/get_profile_image/GetProfileImageResponse.kt
app/src/main/java/com/msg/gcms/data/remote/network/api/UserAPI.kt
app/src/main/java/com/msg/gcms/data/repository/UserRepositoryImpl.kt
app/src/main/java/com/msg/gcms/domain/data/user/get_profile_image/GetProfileImageData.kt
app/src/main/java/com/msg/gcms/domain/repository/UserRepository.kt
app/src/main/java/com/msg/gcms/domain/usecase/user/GetProfileImageUseCase.kt
app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/main/MainActivity.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/MainViewModel.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_club.xml

- 메인 페이지에서 내 프로필 사진을 가져올 수 있도록 수정합니다.
- ![image](https://user-images.githubusercontent.com/82383983/224197747-709006e4-aa41-400c-9896-a46fc94eab08.png)

🔀 :: (#376) - modify profile image to user profile image

---

app/src/main/java/com/msg/gcms/data/mapper/UserMapper.kt
app/src/main/java/com/msg/gcms/data/remote/datasource/user/UserDataSource.kt
app/src/main/java/com/msg/gcms/data/remote/datasource/user/UserDataSourceImpl.kt
app/src/main/java/com/msg/gcms/data/remote/dto/user/get_profile_image/GetProfileImageResponse.kt
app/src/main/java/com/msg/gcms/data/remote/network/api/UserAPI.kt
app/src/main/java/com/msg/gcms/data/repository/UserRepositoryImpl.kt
app/src/main/java/com/msg/gcms/domain/data/user/get_profile_image/GetProfileImageData.kt
app/src/main/java/com/msg/gcms/domain/repository/UserRepository.kt
app/src/main/java/com/msg/gcms/domain/usecase/user/GetProfileImageUseCase.kt
app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/intro/IntroActivity.kt
app/src/main/java/com/msg/gcms/presentation/view/main/MainActivity.kt
app/src/main/java/com/msg/gcms/presentation/view/withdrawal/WithdrawalDialog.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/MainViewModel.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_club.xml
app/src/main/res/layout/logout_dialog.xml

로그아웃 및 회원가입의 클릭 범위를 넓힙니다.
로그아웃 이후 인트로 액티비티에서 완전히 앱이 종료되지 않는 버그 해결

🔀 :: (#382) 로그아웃 및 회원가입 클릭 범위 넓히기

---

app/src/main/java/com/msg/gcms/presentation/utils/ShimmerEvent.kt
app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/club/detail/DetailFragment.kt
app/src/main/java/com/msg/gcms/presentation/view/main/MainActivity.kt
app/src/main/java/com/msg/gcms/presentation/view/profile/ProfileActivity.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/MainViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/ProfileViewModel.kt

스켈레톤이 가끔씩 종료되지 않는 오류를 해결했습니다.
헤더가 남아있어 ui가 깨지는 오류 해결

🔀 :: (#386) 스켈레톤 종료되지 않는 오류 해결

---

app/build.gradle.kts

2.1.0 버전으로 업데이트하고, 이슈들을 수정한 코드를 수합하여 aab 파일을 추출합니다.

🔀 :: version up to 2.1.0

---

app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt

- Interceptor의 ignore path를 수정했습니다

🔀 :: (#393) - ignore path수정

---

.github/workflows/android-cd.yml
.github/workflows/android-ci.yml

🔀 :: (#395) CD 세팅

---

app/build.gradle.kts

🔀 :: (399) 2.1.1 version upgrade

---

.github/workflows/android-cd.yml

service_account파일을 따로 생성 후 넣어줬습니다.

🔀 :: (#395) service_account 파일 따로 삽입

---

.github/workflows/android-cd.yml

service_account 파일을 따로 생성 후 넣어줍니다.

🔀 :: service_account 파일 생성 방식 변경

---

app/build.gradle.kts
app/src/main/java/com/msg/gcms/data/local/dao/ClubDao.kt
app/src/main/java/com/msg/gcms/data/local/database/GCMSDataBase.kt
app/src/main/java/com/msg/gcms/data/local/datasource/club/ClubLocalDataSource.kt
app/src/main/java/com/msg/gcms/data/local/datasource/club/ClubLocalDataSourceImpl.kt
app/src/main/java/com/msg/gcms/data/local/entity/ClubEntity.kt
app/src/main/java/com/msg/gcms/data/mapper/ClubMapper.kt
app/src/main/java/com/msg/gcms/data/remote/datasource/club/ClubDataSourceImpl.kt
app/src/main/java/com/msg/gcms/data/repository/ClubRepositoryImpl.kt
app/src/main/java/com/msg/gcms/di/module/LocalDataSourceModule.kt
app/src/main/java/com/msg/gcms/di/module/LocalModule.kt
app/src/main/java/com/msg/gcms/domain/repository/ClubRepository.kt
app/src/main/java/com/msg/gcms/presentation/view/club/ClubFragment.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/ClubViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/MainViewModel.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/util/Event.kt
app/src/main/java/com/msg/gcms/presentation/viewmodel/util/HttpStatus.kt
buildSrc/src/main/java/Dependency.kt
buildSrc/src/main/java/Versions.kt

내용을 적어주세요.
마카로니 적용해서 로컬에 저장 후 화면에 출력
https://user-images.githubusercontent.com/82383983/231751279-63bb3969-79d3-4340-abcb-0990c4a0235b.mov

🔀 :: (#409) - store data to local from remote

---

app/src/main/java/com/msg/gcms/data/remote/dto/auth/request/RefreshRequest.kt
app/src/main/java/com/msg/gcms/data/remote/network/LoginInterceptor.kt
app/src/main/java/com/msg/gcms/di/module/NetworkModule.kt

refreshToken이 만료되기 전까지 만료된 accessToken이 사용될 때 갱신시켜주기 
- accessToken 갱신 로직
```kotlin
val reAccessToken = authDataStorage.getAccessToken()
val reAccessRequest = chain.request()
.newBuilder()
.addHeader("Authorization", "Bearer $reAccessToken")
.build()
return chain.proceed(reAccessRequest)
```
- RefreshRequest.toRequestBody() 로직 변경
```kotlin
fun RefreshRequest.toRequestBody() =
JSONObject().apply {
put("token", this@toRequestBody.token)
}.toString().toRequestBody("application/json".toMediaTypeOrNull())
```

🔀 :: (#421) - The auto login is so short 

---

app/src/main/res/drawable/bg_period_btn.xml
app/src/main/res/drawable/bg_period_btn_check.xml
app/src/main/res/drawable/bg_period_btn_color.xml
app/src/main/res/drawable/ic_attend_absent.xml
app/src/main/res/drawable/ic_attend_check.xml
app/src/main/res/drawable/ic_attend_late.xml
app/src/main/res/drawable/ic_attend_sick.xml
app/src/main/res/layout/activity_attend.xml
app/src/main/res/layout/attend_dialog.xml
app/src/main/res/layout/dialog_period.xml
app/src/main/res/layout/list_member_attend.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml

내용을 적어주세요.
출석 페이지를 다시 퍼블리싱합니다
- 내용을 적어주세요.

:twisted_rightwards_arrows: :: (#438) - Re_publishing club attend page
